name: control-dsl
version: 0.2.0.2
github: Atry/Control.Dsl
license: BSD3
category: Control, DSL, Effect, General, Language, Mutable State, IO, Polymorphism
synopsis: An alternative to monads
author: Yang Bo
maintainer: pop.atry@gmail.com
copyright: 2018 Yang Bo
extra-source-files:
  - ChangeLog.md
description: |
  This \"control-dsl\" package is a toolkit to create extensible Domain Specific Languages in @do@-notation.

  See "Control.Dsl" for more information.
dependencies:
  - base >= 4.8 && < 5
library:
  source-dirs: src
  other-modules:
    - Control.Dsl.Dsl
    - Control.Dsl.State.State
  other-extensions:
    - RebindableSyntax
    - MultiParamTypeClasses
    - TypeOperators
    - FlexibleInstances
    - FlexibleContexts
    - UndecidableInstances
    - RankNTypes
    - GADTs
tests:
  doctests:
    main: doctest-driver.hs
    source-dirs: test
    ghc-options:
      - "-threaded"
      - "-rtsopts"
      - "-with-rtsopts=-N"
    dependencies:
      - control-dsl
      - containers
      - temporary
      - doctest
      - doctest-discover
    other-extensions:
      - TypeApplications
