name: do-notation-dsl
version: 0.1.0.2
github: Atry/do-notation-dsl
license: BSD3
category: Control, DSL, Effect, General, Language, Mutable State, IO, Polymorphism
synopsis: An alternative to monads
author: Yang Bo
maintainer: pop.atry@gmail.com
copyright: 2018 Yang Bo
extra-source-files:
  - README.md
  - ChangeLog.md
description: 'Please see the README on GitHub at <https://github.com/Atry/do-notation-dsl#readme>'
dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  other-modules:
    - Control.Dsl.Dsl
  other-extensions:
    - RebindableSyntax
    - MultiParamTypeClasses
    - TypeOperators
    - FlexibleInstances
    - FlexibleContexts
    - UndecidableInstances
    - RankNTypes
    - GADTs
    - ScopedTypeVariables
tests:
  doctests:
    main: doctest-driver.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - do-notation-dsl
      - containers
      - temporary
      - doctest
      - doctest-discover
    other-extensions:
      - TypeApplications
