name: Haskell CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'


jobs:
  build:
    strategy:
      matrix:
        resolver:
        - lts-12
        - lts-13
        - lts-14
        - lts-15
        - lts-16
        - lts-17
        - lts-17
        - nightly
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mstksg/setup-stack@v2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-work-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-work-${{ matrix.resolver }}-
          ${{ runner.os }}-stack-work-
    - name: Install dependencies
      run: stack --resolver ${{ matrix.resolver }} test --haddock --no-haddock-deps --dependencies-only --fast
    - name: Build and test
      run: stack --resolver ${{ matrix.resolver }} test --haddock --no-haddock-deps
